openapi: "3.0.2"

info:
  version: 1.0.0
  title: Mini CRM API

servers:
  - description: Dev
    url: localhost:3000

tags:
  - name: Contact
  - name: Tag

paths:
  /api/v1/contacts:
    post:
      tags:
        - Contact
      summary: Create a new Contact
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: "schemas/api/v1/contact/create_request.schema.json"
            examples:
              new-contact:
                summary: A new Contact
                value:
                  $ref: "examples/api/v1/contact/create_request.example.json"
      responses:
        201:
          description: Contact Created Response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/contact/create_response.schema.json"
              examples:
                response:
                  summary: A newly created Contact
                  value:
                    $ref: "examples/api/v1/contact/create_response.example.json"
        422:
          description: Contact Creation Failed Response
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/contact/create_request_error.example.json"
    get:
      tags:
        - Contact
      summary: List Contacts
      parameters:
        - in: path
          name: tag
          schema:
            type: string
          required: false
          description: An optional filter on Tag name
      responses:
        200:
          description: Contacts index response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/contact/index_response.schema.json"
              examples:
                response:
                  summary: Contacts
                  value:
                    $ref: "examples/api/v1/contact/index_response.example.json"
  /api/v1/contacts/:contact_uuid:
    patch:
      tags:
        - Contact
      summary: Update a Contact
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: "schemas/api/v1/contact/update_request.schema.json"
            examples:
              new-contact:
                summary: A new Contact
                value:
                  $ref: "examples/api/v1/contact/update_request.example.json"
      responses:
        200:
          description: Contact Updated Response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/contact/update_response.schema.json"
              examples:
                response:
                  summary: A newly created Contact
                  value:
                    $ref: "examples/api/v1/contact/update_response.example.json"
        404:
          description: Contact Not Found
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/contact/update_request_error.example.json"
    delete:
      tags:
        - Contact
      summary: Delete a Contact
      responses:
        204:
          description: Contact Deleted Response
        404:
          description: Contact Not Found
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/contact/delete_request_error.example.json"
  
  /api/v1/tags:
    post:
      tags:
        - Tag
      summary: Find or Create a Tag
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: "schemas/api/v1/tag/create_request.schema.json"
            examples:
              new-tag:
                summary: A new Tag
                value:
                  $ref: "examples/api/v1/tag/create_request.example.json"
      responses:
        200:
          description: Tag Created or Found Response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/tag/create_response.schema.json"
              examples:
                response:
                  summary: A new Tag
                  value:
                    $ref: "examples/api/v1/tag/create_response.example.json"
        422:
          description: Tag Creation Failed Response
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/tag/create_request_error.example.json"
    get:
      tags:
        - Tag
      summary: List Tags
      responses:
        200:
          description: Tags index response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/tag/index_response.schema.json"
              examples:
                response:
                  summary: Tags
                  value:
                    $ref: "examples/api/v1/tag/index_response.example.json"
  /api/v1/tags/:tag_uuid:
    patch:
      tags:
        - Tag
      summary: Update a Tag
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: "schemas/api/v1/tag/update_request.schema.json"
            examples:
              new-tag:
                summary: A new Tag
                value:
                  $ref: "examples/api/v1/tag/update_request.example.json"
      responses:
        200:
          description: Tag Updated Response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/tag/update_response.schema.json"
              examples:
                response:
                  summary: A newly created Tag
                  value:
                    $ref: "examples/api/v1/tag/update_response.example.json"
        404:
          description: Tag Not Found
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/tag/update_request_error.example.json"
    delete:
      tags:
        - Tag
      summary: Delete a Tag
      responses:
        204:
          description: Tag Deleted Response
        404:
          description: Tag Not Found
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/tag/delete_request_error.example.json"
