openapi: "3.0.2"

info:
  version: 1.0.0
  title: Mini CRM API

servers:
  - description: Dev
    url: localhost:3000

tags:
  - name: Contact
paths:
  /api/v1/contacts:
    post:
      tags:
        - Contact
      summary: Create a new Contact
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: "schemas/api/v1/contact/create_request.schema.json"
            examples:
              new-contact:
                summary: A new Contact
                value:
                  $ref: "examples/api/v1/contact/create_request.example.json"
      responses:
        200:
          description: Contact Created Response
          content: 
            application/vnd.api+json:
              schema:
                $ref: "schemas/api/v1/contact/create_response.schema.json"
              examples:
                response:
                  summary: A newly created Contact
                  value:
                    $ref: "examples/api/v1/contact/create_response.example.json"
        404:
          description: Contact Creation Failed Response
          content:
            application/vnd.api+json:
              examples:
                errors:
                  summary: Errors response
                  value:
                    $ref: "examples/api/v1/contact/create_request_error.example.json"